Create HO-Strategy005.py
freqtrade/freqtrade-strategies pull request #134
Opened 2021-03-15 11:48 UTC by OtenMoten

## Summary
Regarding to `Strategy005.py` in https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/Strategy005.py I've created a hyperopt for this strategy. 

## Upcoming
I will manage this hyperopt actively because I run it live.

## Solving an issue
In the strategy from https://github.com/mishaker, special thanks to @mishaker, there are certain parameter values inserted and I like to get the most perfect values based on the pairs in my config file in a certain timerange.

## Special notes
The strategy from @mishaker and my hyperopt is designed for the 5m timeframe.

2021-03-15 18:37 UTC, xmatthias requested changes
What i'm kindof missing is the actual strategy this goes along with ...

is it still with Stragtegy005, or was that just an inspiration and it's really a derivative (which will also require a different strategy file?)

If it's for Strategy005, maybe put that in the docstring - just so it's clear (I've been reading the comments over and over, and it really wasn't clear.

2021-03-15 18:37 UTC, xmatthias commented on user_data/hyperopts/HO-Strategy005.py
> +        > https://www.vultr.com/?ref=8806640
i would like to not put referal links into strategies / hyperopt files.

we don't have them anywhere else (as far as i know) - and by incorporating these in the repository, it would mean that we recommend them - which i can't (because i never used them).

2021-03-15 18:37 UTC, xmatthias commented on user_data/hyperopts/HO-Strategy005.py
> +        buyTriggerList = ["True"]
Don't do this ... but instead remove / comment this from the space if it only contains one value 

While you'll think it's just one option, so it'll not do anything - scikit-optimize will still consider it as a value to optimize - and it will therefore consume CPU.

2021-03-28 13:23 UTC, OtenMoten commented on user_data/hyperopts/HO-Strategy005.py
> +        > https://www.vultr.com/?ref=8806640
You are absolute right.

2021-03-28 13:23 UTC, OtenMoten commented on user_data/hyperopts/HO-Strategy005.py
> +        > https://www.vultr.com/?ref=8806640
But's it's pretty cool hoster :-)

2021-03-28 13:23 UTC, OtenMoten commented on user_data/hyperopts/HO-Strategy005.py
> +        buyTriggerList = ["True"]
OK, let's remove it.

2021-03-28 13:25 UTC, OtenMoten commented
Updated Swing-High-To-Sky hyperopt and strategy file.

2021-03-28 13:27 UTC, OtenMoten commented
> What i'm kindof missing is the actual strategy this goes along with ...
> 
> is it still with Stragtegy005, or was that just an inspiration and it's really a derivative (which will also require a different strategy file?)
> 
> If it's for Strategy005, maybe put that in the docstring - just so it's clear (I've been reading the comments over and over, and it really wasn't clear.

I already did this on line 24 to 26.

2021-03-29 05:01 UTC, xmatthias approved these changes
i did remove the referral code ... simply marking the conversation to "resolved" does not remove it from the file ... 

LGTM :+1:

2021-03-29 05:01 UTC, merged