MultiMa Strategy
freqtrade/freqtrade-strategies pull request #164
Opened 2021-04-26 19:52 UTC by mablue

## Summary
Its an strategy for find best Multiple ma conditions mix for trading 

## Quick strategy idea
the strategy compare multiple simple moving averages to find best place to trading.
it will also check the previous candles to get better results

2021-04-27 04:43 UTC, xmatthias requested changes

2021-04-27 04:43 UTC, xmatthias commented on user_data/hyperopts/MultiMaHo.py
> +                            dataframe[f'buy-ma-{i}'].shift(shift) > dataframe[f'buy-ma-{i-1}'].shift(shift))
In general, you should do indicator calculations in `populate_indicators`, not in `popuplate_buy` for performance reasons.

Otherwise, the same calculation (say `ta.SMA(dataframe, 20)`) is executed potentially 100ds of times (while all other indicators change) - making hyperopt go a lot slower than what would be necessary.

You can find a sample of that here: https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/AverageHyperopt.py


In general, i'd encourage to have a look at the new hyperopt interface [using parameters](https://www.freqtrade.io/en/latest/hyperopt/#hyperoptable-parameters) which will be in the next release - which will make the need to create hyperopt files unnecessary in most cases, and will simplify and reduce the amount of code you'll need for this by about "1 hyperopt file" :laughing:

2021-04-27 06:51 UTC, mablue commented on user_data/hyperopts/MultiMaHo.py
> +                            dataframe[f'buy-ma-{i}'].shift(shift) > dataframe[f'buy-ma-{i-1}'].shift(shift))
Ok.sorry  I will fix it.
Yes Its good idea to rediuce strategy and hyperopt to one file.

 cuz my strategys and hyperopts almost are a copy version of togedir.

2021-04-28 17:25 UTC, mablue commented on user_data/hyperopts/MultiMaHo.py
> +                            dataframe[f'buy-ma-{i}'].shift(shift) > dataframe[f'buy-ma-{i-1}'].shift(shift))
New Changes Available now for GodStra.
I think multi tf problem fixed with new godStra and no need to them for now!!

2021-04-28 17:25 UTC, mablue commented
New Changes Available now for GodStra.
I think multi tf problem fixed with new godStra and no need to them for now!!

2021-05-03 00:27 UTC, vulcandth commented
Testing out the new GodStraHoHo.py file using embedded instructions results in all hyperopt epochs produce the same result. 

freqtrade hyperopt-list 
```|        |   75/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
|        |   76/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
|        |   77/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
|        |   78/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
|        |   79/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
|        |   80/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
+--------+---------+----------+------------------+--------------+------------------------------+----------------+-------------+

Best result:

*    1/80:     17 trades. 10/7/0 Wins/Draws/Losses. Avg profit   1.41%. Median profit   0.95%. Total profit  4.79372407 USD (  23.94Σ%). Avg duration 227.6 min. Objective: -5.74667


    # Buy hyperspace params:
    buy_params = {
     'buy-real-0': 0.86825
    }

    # Sell hyperspace params:
    sell_params = {
     'sell-real-1': 0.58537
    }```

GodStraHoHo.py
```# --- Do not remove these libs ---
from functools import reduce
from typing import Any, Callable, Dict, List

import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from skopt.space import Categorical, Dimension, Integer, Real  # noqa

from freqtrade.optimize.hyperopt_interface import IHyperOpt

# --------------------------------
# Add your lib to import here
import talib.abstract as ta  # noqa
import freqtrade.vendor.qtpylib.indicators as qtpylib
# this is your trading strategy DNA Size
# you can change it and see the results...
# A real number(0.01~0.99)
searchRange = .5
# past all generated buy and sell params (from GodStraHo) here:

# **************************************** Copy Generated Strategy params here *************************************************
# Buy hyperspace params:
buy_params = {
        'buy-cross-0': 'TAN-14',
        'buy-cross-1': 'CDLLADDERBOTTOM-7',
        'buy-cross-2': 'CDLDOJI-7',
        'buy-indicator-0': 'SUB-14',
        'buy-indicator-1': 'CDLHARAMI-14',
        'buy-indicator-2': 'CDLHIGHWAVE-14',
        'buy-int-0': 3,
        'buy-int-1': 69,
        'buy-int-2': 40,
        'buy-oper-0': '<R',
        'buy-oper-1': 'CA',
        'buy-oper-2': 'D',
        'buy-real-0': 0.87404,
        'buy-real-1': -0.5932,
        'buy-real-2': -0.25014
}

# Sell hyperspace params:
sell_params = {
        'sell-cross-0': 'CDLUPSIDEGAP2CROWS-14',
        'sell-cross-1': 'ROCP-7',
        'sell-cross-2': 'TANH-7',
        'sell-indicator-0': 'STOCHRSI0-7',
        'sell-indicator-1': 'TRIX-14',
        'sell-indicator-2': 'CDLMORNINGDOJISTAR-7',
        'sell-int-0': 56,
        'sell-int-1': 74,
        'sell-int-2': 18,
        'sell-oper-0': 'CB',
        'sell-oper-1': '<R',
        'sell-oper-2': 'CA',
        'sell-real-0': 1.00042,
        'sell-real-1': 0.86132,
        'sell-real-2': 0.50527
}
# ******************************************************* End ******************************************************************```

2021-05-03 05:41 UTC, mablue commented
> Testing out the new GodStraHoHo.py file using embedded instructions results in all hyperopt epochs produce the same result.
> 
> freqtrade hyperopt-list
> 
> ```
> |        |   76/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
> |        |   77/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
> |        |   78/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
> |        |   79/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
> |        |   80/80 |       17 |     10    7    0 |        1.41% |    4.79372407 USD   (23.94%) |        227.6 m |    -5.74667 |
> +--------+---------+----------+------------------+--------------+------------------------------+----------------+-------------+
> 
> Best result:
> 
> *    1/80:     17 trades. 10/7/0 Wins/Draws/Losses. Avg profit   1.41%. Median profit   0.95%. Total profit  4.79372407 USD (  23.94Σ%). Avg duration 227.6 min. Objective: -5.74667
> 
> 
>     # Buy hyperspace params:
>     buy_params = {
>      'buy-real-0': 0.86825
>     }
> 
>     # Sell hyperspace params:
>     sell_params = {
>      'sell-real-1': 0.58537
>     }```
> 
> GodStraHoHo.py
> ```# --- Do not remove these libs ---
> from functools import reduce
> from typing import Any, Callable, Dict, List
> 
> import numpy as np  # noqa
> import pandas as pd  # noqa
> from pandas import DataFrame
> from skopt.space import Categorical, Dimension, Integer, Real  # noqa
> 
> from freqtrade.optimize.hyperopt_interface import IHyperOpt
> 
> # --------------------------------
> # Add your lib to import here
> import talib.abstract as ta  # noqa
> import freqtrade.vendor.qtpylib.indicators as qtpylib
> # this is your trading strategy DNA Size
> # you can change it and see the results...
> # A real number(0.01~0.99)
> searchRange = .5
> # past all generated buy and sell params (from GodStraHo) here:
> 
> # **************************************** Copy Generated Strategy params here *************************************************
> # Buy hyperspace params:
> buy_params = {
>         'buy-cross-0': 'TAN-14',
>         'buy-cross-1': 'CDLLADDERBOTTOM-7',
>         'buy-cross-2': 'CDLDOJI-7',
>         'buy-indicator-0': 'SUB-14',
>         'buy-indicator-1': 'CDLHARAMI-14',
>         'buy-indicator-2': 'CDLHIGHWAVE-14',
>         'buy-int-0': 3,
>         'buy-int-1': 69,
>         'buy-int-2': 40,
>         'buy-oper-0': '<R',
>         'buy-oper-1': 'CA',
>         'buy-oper-2': 'D',
>         'buy-real-0': 0.87404,
>         'buy-real-1': -0.5932,
>         'buy-real-2': -0.25014
> }
> 
> # Sell hyperspace params:
> sell_params = {
>         'sell-cross-0': 'CDLUPSIDEGAP2CROWS-14',
>         'sell-cross-1': 'ROCP-7',
>         'sell-cross-2': 'TANH-7',
>         'sell-indicator-0': 'STOCHRSI0-7',
>         'sell-indicator-1': 'TRIX-14',
>         'sell-indicator-2': 'CDLMORNINGDOJISTAR-7',
>         'sell-int-0': 56,
>         'sell-int-1': 74,
>         'sell-int-2': 18,
>         'sell-oper-0': 'CB',
>         'sell-oper-1': '<R',
>         'sell-oper-2': 'CA',
>         'sell-real-0': 1.00042,
>         'sell-real-1': 0.86132,
>         'sell-real-2': 0.50527
> }
> # ******************************************************* End ******************************************************************```
> ```

Cuz the strategy reached to the end of hish optimization limits!
You can change searcharea variable to check big range of numbers.
Let check your strategy on margin or futures market with x200 leverage!if its completely loose less!(kidding)
See you on the moon.

2021-05-05 06:18 UTC, xmatthias commented
This PR is constantly changing - which makes reviewing it very difficult.
Please let me know when the changes will be done so i will review it - otherwise it won't make sense to me to review it as every day there's things that change - which tells me that this is a WIP - and nothing that is ready to be merged.

you should also not use commit messages like `Indicators Normalized!!! FFFFFFFFFFFFFFFfffffffffffffffuuuu*****` .... but i guess that can be fixed by doing a squash commit.

2021-05-05 09:15 UTC, mablue commented
Okey now everything is fixed!;)
I will miss ta library and his indicators...:(
I want to make it again in another godStrategy...

2021-05-05 10:03 UTC, mablue commented
New Strategies Added
ADXMomentum Hyperopt added
GodStra SpeedUp
GodStra Indicators Normalization.
No need To ta Now(calculation returned to ta-lib)
Fixed bugs And Errors of missing data.No need to Agefilter now

2021-05-05 14:52 UTC, mablue commented
Hyperopt algo fixed
New Strategies Added
ADXMomentum Hyperopt added
GodStra SpeedUp
GodStra Indicators Normalization.
No need To ta Now(calculation returned to ta-lib)
Fixed bugs And Errors of missing data.No need to Agefilter now

2021-05-10 17:27 UTC, xmatthias requested changes
The naming of certain parameters (buy_params, sell_params) is missleading and suggests that you're using Hyperoptable parameters, which are however not used.

Please either use different variable names - or switch to the new format (recommended) - which will also make the hyperopt-files unnecessary.

2021-05-11 07:13 UTC, mablue commented
> The naming of certain parameters (buy_params, sell_params) is missleading and suggests that you're using Hyperoptable parameters, which are however not used.
> 
> Please either use different variable names - or switch to the new format (recommended) - which will also make the hyperopt-files unnecessary.

yes Im working on it befour but I have a big problem with dynamic count of hyperoptable variables that shoud be generated at first line of the class.
I 2times write a code and remove whole of writen code again cuz of that.
I tryd first to add a def in this hyperopt file to generate hyperoptable params inside it.but while hyperoption of strategy I get an error that says it cant find any hyperoptable parameter! for values used in buy and sell conditions!
The hyperopting command cant see hyperoptable params are inside a def and will generate after callig this def from indicator populator!!
secend time I try to split def and eject the pice of variable generator of main " forloop rang(dnaSize) " outside the condition generator def but still I get some errors and bunch of complexity that cant handle by my mind!
I Will re write the code that I removed, here to get your help.tnx

2021-05-11 07:20 UTC, mablue commented on user_data/strategies/berlinguyinca/ADXMomentum.py
> +    }
ok I will change it and will remove the hyperopt file too;)

2021-05-11 07:23 UTC, mablue commented on user_data/strategies/Zeus.py
> +    }
yes I will change them to new method but still I have fair about godStraHo It have a complex hyperopt algorithm that Still I cant find a way to write it in new format

2021-05-15 06:19 UTC, xmatthias reviewed
I would not be using `RealParameter` (unless there's a very good reason to) - as it's space is very large (16 decimals is no fun - and usually not useful either).

Also - for the future: 
please create a new branch in your repository for a pull request.
Make one branch / Pull request per strategy (combined PR's like this will usually take a long time to review, and to merge - as one problematic strategy can delay merging of all other strategies).

If you need some instructions on how to do that with github, maybe use the [github flow](https://guides.github.com/introduction/flow/) to get some guidelines on how to work with github.

2021-05-15 06:19 UTC, xmatthias commented on user_data/strategies/GodStra.py
> +                    ta.SMA(indicator_dataframe, TREND_CHECK_CANDLES)
This should be calculated as part of populate_indicators and then used throughout this method.

now you're calculating it potentially 100ds of times (once per hyperopt) - which will make hyperopt run rather slow.

2021-05-15 07:41 UTC, mablue commented on user_data/strategies/Zeus.py
> +        0.001, 0.999, default=0.11908, space='buy')
Ooppssz thanks  I will use decimalParam ok

2021-05-15 07:47 UTC, mablue commented on user_data/strategies/GodStra.py
> +                    ta.SMA(indicator_dataframe, TREND_CHECK_CANDLES)
Ops yes I will do that . Wowwowowowowo

2021-05-16 08:27 UTC, closed without merging