wtc strategy added
freqtrade/freqtrade-strategies pull request #196
Opened 2021-06-05 11:29 UTC by mablue

# WTC Strategy: WTC(World Trade Center Tabriz)
# is the biggest skyscraper of Tabriz, city of Iran
# (What you want?it not enough for you?that's just it!)
# No, no, I'm kidding. It's also mean Wave Trend with Crosses
# algo by LazyBare(in TradingView) that I reduce it
# signals noise with dividing it to Stoch-RSI indicator.
# Also thanks from discord: @aurax for his/him
# request to making this strategy.
# hope you enjoy and get profit
# Author: @Mablue (Masoud Azizi)
# IMPORTANT: install sklearn befoure you run this strategy:
# pip install sklearn
# github: https://github.com/mablue/
# freqtrade hyperopt --hyperopt-loss SharpeHyperOptLoss --spaces buy sell --strategy wtc

https://www.pinterest.com/search/pins/?q=tabriz&rs=typed&term_meta[]=tabriz%7Ctyped
https://en.wikipedia.org/wiki/Mohammad-Hossein_Shahriar

2021-06-05 12:34 UTC, xmatthias requested changes

2021-06-05 12:34 UTC, xmatthias commented on user_data/strategies/wtc.py
> +            min_max_scaler = preprocessing.MinMaxScaler()
That's a no-go.
If you run backtesting with this, it'll use the full data range for scaling - so it's implicitly creating a lookahead bias by using the full data.

Think about a pair that had big raises (say BTC) - and you backtest for 2 years. The first year will be scaled to 0.0-0.03 - while the remaining might be scaled to 0.03-1.0 ... as such - it's a lookahead as the scaler knows what the maximum (in the future!) has been.

2021-06-05 12:45 UTC, mablue commented on user_data/strategies/wtc.py
> +            min_max_scaler = preprocessing.MinMaxScaler()
ops! than I think I will
normalize just oscillators.;) sorry

2021-06-05 13:03 UTC, xmatthias commented on user_data/strategies/wtc.py
> +            min_max_scaler = preprocessing.MinMaxScaler()
Just normalizing the oscillators would work - but it's not what you're doing. 
`wt1` and `wt2` are not oscillators - but reflect the price - and as such - you cannot scale them to be reliably between 0 and 1 (because that will always require you to know the final value - which you can't as you're then doing lookahead.

2021-06-05 13:58 UTC, mablue commented on user_data/strategies/wtc.py
> +            min_max_scaler = preprocessing.MinMaxScaler()
yes maybe them are not oscillators I seen befour examples that go down and down and still down more and more!
but if you add this indicator on tradingview you can see its halfly works like an oscillators.and yes just normalizing is ok for making profit.check it:
https://www.tradingview.com/script/jFQn4jYZ-WaveTrend-with-Crosses-LazyBear/

2021-06-07 17:51 UTC, mablue commented on user_data/strategies/wtc.py
> +            min_max_scaler = preprocessing.MinMaxScaler()
Is there still other problems?!

2021-06-08 19:37 UTC, mablue commented on user_data/strategies/wtc.py
> +            min_max_scaler = preprocessing.MinMaxScaler()
![Screenshot_20210609-000348](https://user-images.githubusercontent.com/5004900/121246705-b0c16700-c8b6-11eb-82f6-7226171d4ebb.png)

2021-06-10 04:50 UTC, xmatthias commented on user_data/strategies/wtc.py
> +from freqtrade.strategy.hyper import DecimalParameter
You should remove this import - it's imported twice (and this is the wrong, undocumented import, so internal freqtrade changes might break this line).

2021-06-10 04:53 UTC, mablue commented on user_data/strategies/wtc.py
> +from freqtrade.strategy.hyper import DecimalParameter
oh sorry I dont know why vscode add this things without asking me :( i will disable auto imports but its not bad sometimes to use.
vscode is growing like a deracula and didnt see his mistakes

2021-06-10 04:56 UTC, xmatthias commented on user_data/strategies/wtc.py
> +from freqtrade.strategy.hyper import DecimalParameter
vscode usually imports from the "direct" path. While that's not per se wrong - (and vscode shouldn't add this import if you had it already there before) - it might lead to problems down the road (we export things form the .strategy package intentionally - to avoid having users import from everywhere in the package, which would hinder refactorings.

2021-06-10 17:26 UTC, xmatthias approved these changes
:+1:

2021-06-10 17:27 UTC, merged