heracles in New API, Bugs fixed
freqtrade/freqtrade-strategies pull request #202
Opened 2021-06-26 22:44 UTC by mablue

heracless strategy/hyperopt upgraded to New API
bugs fixed #201

2021-06-27 08:48 UTC, xmatthias commented on user_data/strategies/Heracles.py
> +    df = (df-df.min())/(df.max()-df.min())
You'll need to be careful with such approaches.

I understand you try to normalize this - but this will give totally different results between backtesting and live as it's looking at the full dataframe (and as such - is look-ahead biased / using data it should not).

2021-06-27 08:49 UTC, xmatthias commented on user_data/strategies/Heracles.py
> +    sell_atol = DecimalParameter(1.e-16, 1.e-0, default=0.00019, decimals=10, space='sell')
I find this space overly large.
You'll not find any (added) value after 4 or 5  decimals - so using decimals=10 will inflate the search-space (slow down hyperoptimization) without providing any real benefit.

2021-06-27 11:33 UTC, mablue commented on user_data/strategies/Heracles.py
> +    df = (df-df.min())/(df.max()-df.min())
yee this normalization is very usefull but just in oscilators not in indicators like sma or etc that have not a standard min & max.
also if you mean full dataframe : all columns. not it just 4 indicators that normalised that all of them has not following price and have min/max as well.
and we have not the problems like befour for this. see lines 87 and etc..

2021-06-27 11:37 UTC, mablue commented on user_data/strategies/Heracles.py
> +    sell_atol = DecimalParameter(1.e-16, 1.e-0, default=0.00019, decimals=10, space='sell')
yes I will fix it.i just do that cuz of having some coins that have very small prices like trtl/btc= 0.0000000000001 but ye we there just have indicators and no need to price comparison

2021-06-27 13:07 UTC, xmatthias requested changes
Unfortunately, the normalization serves as a bad example - which can lead others to use it wrongly assuming it's something it isn't - and as such - please change that to something that either applies specifically to the indicator you're using - or to a method that does not suffer from the lookahead bias problem.

2021-06-27 13:07 UTC, xmatthias commented on user_data/strategies/Heracles.py
> +    df = (df-df.min())/(df.max()-df.min())
unfortunately, that's not true.
Assuming an oscillator like RSI (ranges from 0 to 100) for simplicity - it will apply to all other oscillators as well.

By scaling it to "dataframe's min/max" - you're scaling it to the dataframe's min/max values.
Assuming for backtesting - these will very likely be close to 100 and close to 0 (with a big enough time-range).
if you now do the same for only 500 candles each - it will heavily depend - you'll sometimes get it scaled between 40 and 100 ... sometimes between 30 and 60 ... 

you'll simply not know - but as you're using the scaled / normalized values - you'll work off of a wrong assumption.

If you only apply it to oscillators - then their absolute upper and lower limit must be known to you - so use that instead of using `.min()` and `.max()` (if they have unknown upper/lower limits, they're not really oscillators - they just look like oscillators).

2021-06-27 22:24 UTC, mablue commented
> Unfortunately, the normalization serves as a bad example - which can lead others to use it wrongly assuming it's something it isn't - and as such - please change that to something that either applies specifically to the indicator you're using - or to a method that does not suffer from the lookahead bias problem / or rather (to be more precise) - to something that generates the same result for today, 10:00 - no matter if i'm using 500 candles - or 50000 candles (which currently, is simply not the case).

I can prementelly remove the normalization.there is no problem when I remove but I will change the limits of dividation values to maybe integer or check the devidation order to devide always smallest/biggest indicator to be allways inside 0~1 and set the limits of devidation to 0~1 and thats it we can use it without normalization.also I will rehype and repreduce defaults to decrese the danger of default usage.thank you for help to improve it ;)

2021-06-27 22:31 UTC, mablue commented on user_data/strategies/Heracles.py
> +    df = (df-df.min())/(df.max()-df.min())
ops yes now I understand what you mean yes if we have just 10 candles in our hands its max and min rsi maybe will be 50~80 and this normalization will get us wrong values.
ok than I can find an optimal min/max to normalize things in it.
for example I can check 10 coins indicators and find the best value to set as min/max for each indicator and than calculate the normalized value.
also if we think honest, in this case our all normalizations in other strategies will preduce wrong values some times!I think I will change all normalization methods in other strategies too!!!

2021-06-27 22:47 UTC, mablue commented on user_data/strategies/Heracles.py
> +    df = (df-df.min())/(df.max()-df.min())
but I think the true way is that I just remove the normalization cuz some indicators have not a min or max and it make problems and also I cant really find all exact min or maxes in all genes in godStra to normalize,
or maybe the best technic to do is that we check the candles that we have and if its smaller than for example 50 we just ingnore it.
and also if a dataset have not 3 Repetitious min and max we will ignore it.and dont normalise it never!
i think the last tecnic will work well @xmatthias  yes?!

2021-06-28 18:08 UTC, xmatthias commented on user_data/strategies/Heracles.py
> +    df = (df-df.min())/(df.max()-df.min())
Looking at part of the dataframe can still cause the same effect (as you won't know which part you're looking at). 
To me, you can't properly normalize (ensure the values are between 1 and 0) unless you know the theoretical maxima's of the indicators - not without either looking into the future, or risking it to eventually flow over if there's some extreme values that didn't happen earlier).

As such (and this is why) i've always been of the opinion that blindly combining indicators without thinking twice (-> let hyperopt do that) is not a good approach.

> also if we think honest, in this case our all normalizations in other strategies will preduce wrong values some times

Not many strategies will use normalizations - and to be honest, i'm looking at your's a bit closer now - as they created more issues than any of the other strategies before :laughing:

2021-06-28 18:22 UTC, mablue commented on user_data/strategies/Heracles.py
> +    df = (df-df.min())/(df.max()-df.min())
maybe if I find a teorical min and max it will fixed but just in oscilators and some others maybe for example patterns that have just 0 and 100 values: but I think I will take care strategyis from unesessery normalizations.
for example in this stra we dont need really a normalization...
yes thank you to looking closer its take more time of you and I know. thanks.✌️😎✌️

2021-07-16 04:34 UTC, xmatthias commented on user_data/strategies/Heracles.py
> +    sell_atol = DecimalParameter(1.e-16, 1.e-0, default=0.00019, decimals=10, space='sell')
I find it interresting that you had this fixed (reduced to 4 decimals) and now put it back.

As mentioned before - using a 10 decimal spaces does not make sense and will overfit the strategy for sure.

2021-07-16 12:43 UTC, mablue commented on user_data/strategies/Heracles.py
> +    sell_atol = DecimalParameter(1.e-16, 1.e-0, default=0.00019, decimals=10, space='sell')
opsss!! I dont know why so soory i will fix it

2021-07-25 20:37 UTC, mablue commented
OK.I changed the decimals also removed sell spaces cuz i think them are not useful and always roi was effective on sell

2021-07-25 20:38 UTC, mablue commented on user_data/strategies/Heracles.py
> +    sell_atol = DecimalParameter(1.e-16, 1.e-0, default=0.00019, decimals=10, space='sell')
@xmatthias OK.I changed the decimals also removed sell spaces cuz i think them are not useful and always roi was effective on sell

2021-07-27 17:58 UTC, xmatthias approved these changes
Great - looks good now :+1:

2021-07-27 17:58 UTC, merged