Brain Stra added
freqtrade/freqtrade-strategies pull request #207
Opened 2021-08-07 20:51 UTC by mablue

```
 @@@@@@@@@@@@@@@@&@#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@, @@/@@@&@@@@@@@@@&@*@@/@.@@(@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@%@*@@/%@&,@@#.@@@@@@#@@,.@@@/ @@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@*##@@ @.@@@&.@@@@@@@.@ &@@& .@@,@@&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@&%@@% @@@  @@% @@@@@@@@@@**& @@@(#,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@&,,. (@% . @@@@@@@@@@@( ,#.,%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@&  @@@@@@@@@@@ (@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@   %@@@@@@( *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@&/*/@@@@@@@@@@@@%             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@%.,&@@%/@@@@@@@@@@                 /@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@( #@@@@@@@/                          ,      #@@@@@@@@@@@@@@@@@@@@@@@@@@
@%#*                                       %@@#          @@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@&. /@@@@@@&                     (@@@@@@@@@@@&.      @@@@@@@@@@@@@@@@@@@@@
@@@@*.&@ @@@@@@@@@%                   @@@@@@@@@@@@@@@@@*,    %@@@@@@@@@@@@@@@@@@
@@@@@@@(@@@@@@@@@                  *@@@@@@@@@@@@@@@@@@@@%     @@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@(   @@@@@@@@@@@@,   #@@@@@@@@@@@@@@@@@@@@@@@%    (@@@@@@@@@@@@@@@@@
@@@@@@@@(  @@@ / (@@@@@@@@@@@@@, &@@@@@@@@@@@@@@@@@@@@@@@#     @@@@@@@@@@@@@@@@@
@@@@@@*@@.@@@ @@ *&,@@@@@@@@@@@* ( %@@@@@@@@@@@@@@@@@@@@@#    .@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@ #@/&,@@#@@@@@@@( %@ (@@@,#@@@@@@@@@@@@@@@@@@@/ .@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@%%&&@#@#@@@@@@@@.@@@@%  ,@@@&%@#@@@@@@@@@@@@@@@     @@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@/@@@@* @&*@@.@@@%@@@@@@@@@@@@@@/     @@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@/@#@@,&@@@@@@@@@@@@@@@@@@@@&     &@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&@@&@@@@@@@@@@@@@@@@@@     &@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@(   #@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.    .@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.     &@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#     @@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,    %@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/   %@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    .@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@     @@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*    (@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@     @@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# %@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@% %@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.  @@@@@@@@% .#* ./,.*%@@%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ &@@@%(/**.%@@@@@@@ &@@@@%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@, &@@@@@@@@@@@ @@@@@@@(*@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#  (@ &@@@@@@@@@@# @@@@@@@@  @@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@% @@@ @@@@,*@@@@@@@@@,@@@(  %@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@(*@@@@@@@# @@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ .@@@@@&*@@@@@@@@@. &@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  &@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

2021-08-08 11:12 UTC, xmatthias requested changes
Please consider the "2 file" hyperopt interface as deprecated, and "to be removed" sometime in the near future.
The "parameter" interface allows the same functionalities, but in a much simpler way for the user (with a lot less doubts and manual effort).


As such - i'll not be accepting any PR's with explicit HO files anymore - and i've already started removing the existing Hyperopt files (migrating their logic to the respective strategies).

2021-08-08 22:33 UTC, mablue commented
ok but you know why I am using 2file method.
for
hyperopting arrays
its necessary

2021-08-09 04:29 UTC, xmatthias commented
Considering that your other strategies (heracles, ...) caused a lot of questions and doubts already, i don't think it's necessary, and will only complicate code that could be expressed in a better way, which makes people understand the strategy.

2021-08-09 05:00 UTC, mablue commented
> Considering that your other strategies (heracles, ...) caused a lot of questions and doubts already, i don't think it's necessary, and will only complicate code that could be expressed in a better way, which makes people understand the strategy.

yes Them had bunch of problems and asking questions but why?
cuz its not mine idea!
heracles and Zeus and etc are the idea of computers and humans not familiar with CPUs. Im In shok as well. I dont know why people cant work with an small one indicator one file strategy.
but you will agree with that the biggest problem of data scientists is that them cant let everything to computers. I try to do that I want to force computer to write his own strategy line by line.I think its amazing but have custs. for example bunch of people that cant undrestand in first. I see them like who that allways have new technology fair.but when them try this new technology them allways will love it and use it. you know what I mean?
I mean our brain cant handle big data but CPUs If we struct them selfcontrolled and give everything in them hands, them can be useful. 
in other hand I know you care about complexity and yes Its a big problem. but its not the main code its just an strategy that works for his own in a side and many people love it I had more more messages that say me please continue and Improve. and why we dont do that If some people confused?!

2021-08-09 05:11 UTC, xmatthias commented
I'm not against this concept in general - the only thing i asked is to do this using the new interface, as we'll probably be dropping support for the explicit hyperopt file later this year.

2021-08-09 05:29 UTC, mablue commented
> I'm not against this concept in general - the only thing i asked is to do this using the new interface, as we'll probably be dropping support for the explicit hyperopt file later this year.
> 
> For that reason - having new explicit hyperopt files now is counter-productive, and would result in removal of this strategy/hyperopt pair in a few months.

I dont love old 2file method too.please remove it.
but I love being strong on writing strategys.
let find a way to do that.
I will try to do something that decrease your fair and attend you to do :))
but Yes now I seen your discord message and I know you didnt agree with it ... ok... ;)
I can find a way to do it without arrays

2021-08-14 06:27 UTC, xmatthias requested changes
Can you explain what makes this different to GodStrat(new) ? 
it seems like it's simply combining all indicators together to extract one value (probably a % of "good or bad?) ... 

Considering that we've been in a bull market for the last 2-3 years (for the most part) - you'll always make profits with a stoploss this wide.
I doubt you'll be able to make good profits when you reduce the stoploss to something below 10% (and remove the lookahead bias) - as this will probably result in a strategy that buys based on one indicator-group - where all basically tell the same story in slightly different terms - which will reinforce each other - without really having learned something.


One thing i'll want to have fixed for sure is the messy variable naming. Otherwise, i'll not be able to accept this (accepting a PR means also taking responsibility to eventually maintain something - which with this messy code, i currently cannot).

2021-08-14 06:27 UTC, xmatthias commented on user_data/strategies/QBitrain.py
> +AllLearntKnowledges = {
Your variable usage is all over the place and makes it very hard to follow the strategy.

For a strategy with this complexity (which i expect to generate a lot of questions again) - please use common Python naming conventions - which will allow others with some python experience to easily identify what each variable corresponds to.

This means: 
* all uppercase for constants (things that are never modified again)
* camelcase for class names
* lowercase (seperated by `_` if it's multi-word) for variables.

2021-08-14 06:27 UTC, xmatthias commented on user_data/strategies/QBitrain.py
> +        RESULT += DFINP*QS
Each of the below can be reduced to 1-2 lines (there's no need for `QS` - nor for `DFINP` (use `dataframe[IND]` for that.

Your way to express this is pretty verbose and makes the strategy appear more complicated than it really is.

2021-08-14 06:27 UTC, xmatthias commented on user_data/strategies/QBitrain.py
> +        # TODO: Its not dry code!
These comments are pointless - if you think this is the case, then please reduce the verbosity (see below).

2021-08-14 06:27 UTC, xmatthias commented on user_data/strategies/QBitrain.py
> +            ).iloc[:, knowledge_index]
Did you verify (for each and every ta-function that's listed in the list above) - that they REALLY have a `timeperiod` attribute?
there's some that don't have that IIRC - so i assume you made sure to not include these?

2021-08-14 06:27 UTC, xmatthias commented on user_data/strategies/QBitrain.py
> +    # Buy hyperspace params:
This result proves what i point out elsewhere - by having a stoploss as wide as this strategy uses, the strategy is based on luck / pairs eventually recovering - not on having learned a lot.

2021-08-14 06:27 UTC, xmatthias commented on user_data/strategies/QBitrain.py
> +    return df
This has a lookahead bias (as mentioned the last time, too).

Results created with this will not realize when using real modes that don't give you the full dataframe.

2021-08-14 06:27 UTC, xmatthias commented on user_data/strategies/QBitrain.py
> +
it's unclear what you try to accomplish here (the comment above hints that you're also not sure).

why multiply things by 2 if the length is 1? that seems pretty much random ...

2021-08-16 19:23 UTC, closed without merging