Multima indexing problems fixed and DUALFIT added
freqtrade/freqtrade-strategies pull request #213
Opened 2021-08-17 13:16 UTC by mablue

it had some indexing problem on calculating conditions that fixed also DUALFIT added to strategy

2021-08-19 18:23 UTC, xmatthias commented on user_data/strategies/MultiMa.py
> +                                              timeperiod=int(i * self.buy_ma_gap.value))
I'm not a huge fan of calculating indicators in the `populate_*_trend()` methods.

You should rather use the [documented approach][https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter) for this.

For hyperopt, this is pretty inefficient and will slow down hyperopt a lot, as this means that EMA1 (or whatever the first value is) will be calculated every single time - so you'll end up calculating the same exact EMA value over and over again (assuming other parameters changed).

By calculating the maximum range (say, from EMA1 to EMA100) in `populate_indicators` - it'll be calculated only once.

2021-08-20 13:48 UTC, mablue commented on user_data/strategies/MultiMa.py
> +                                              timeperiod=int(i * self.buy_ma_gap.value))
I used a new method to fix it. if there is calculated ema it will not calc again!
you can add it inside freqtrade too. I dont know how cuz user can say everything to his calculated indicator. and will his own check inside strategy
but if with a extra interpreter the ta.XXX words checked and than saved inside some file it will very helpfull for calculating non static(dynamic) indicator calculation inside buy and sell strategy..and it make hyperoption speedy.
but I think the only place that this things will needen are inside my strategies. no One uses dynamic calculating indicators nowadays...
But sometimes it use able...in hyperoption its very useable to calculate things right there inside the loop for finding best values  for ta methods

2021-08-20 21:52 UTC, mablue commented on user_data/strategies/MultiMa.py
> +                                              timeperiod=int(i * self.buy_ma_gap.value))
live checked
![Screenshot from 2021-08-21 02-19-18](https://user-images.githubusercontent.com/5004900/130296971-8dc1907e-526f-48bc-b12a-eb79a797cfef.png)

2021-08-21 05:02 UTC, xmatthias commented on user_data/strategies/MultiMa.py
> +                                              timeperiod=int(i * self.buy_ma_gap.value))
seems like the history of that branch is messed up.
Please checkout master and make sure it's uptodate with the repository
```
git checkout master
git fetch origin # (assuming origin is what you use for freqtrade/freqtrade-strategies - otherwise please adujust all usages of this below)
# Ensure origin 
git reset --hard origin/master 

git checkout <yourbranch>

# This might cause merge-conflicts - fix them, stage the files you fixed and move forward with `git rebase --continue`
git rebase master

git push -f
```

2021-08-25 09:45 UTC, mablue commented on user_data/strategies/MultiMa.py
> +                                              timeperiod=int(i * self.buy_ma_gap.value))
Im done some things but I dont know fixed or not?!!

2021-08-25 15:10 UTC, xmatthias requested changes

2021-08-25 15:10 UTC, xmatthias commented on user_data/strategies/MultiMa.py
> +    # DONT TOUCH OR FORMAT ABOVE!
You might comment it this way - but i'l surely not merge a strategy in that has lines this long.
Python has conventions of "one command per line" on purpose.

this is neither understandable nor maintainable, and as such, cannot be accepted.

2021-08-25 16:16 UTC, mablue commented on user_data/strategies/MultiMa.py
> +    # DONT TOUCH OR FORMAT ABOVE!
ok but I think you know why Im do this.
I'll fix it

2021-08-25 16:23 UTC, mablue commented on user_data/strategies/MultiMa.py
> +    # DONT TOUCH OR FORMAT ABOVE!
> ok but I think you know why Im do this.for having clean code!
> I'll fix it

2021-08-29 07:48 UTC, mablue commented
@xmatthias multima will just use 3 ribbons for each  buy and sell. mass conditions fuckd up my mind :|

2021-08-29 09:13 UTC, xmatthias commented on user_data/strategies/MultiMa.py
> +    timeframes = [5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150, 200]
The naming of this variable (timeframes) suggests it's selecting different timeframes (5m, 30m, ...) - but it's actually selecting something completely different.

I think a better name will be appropriate.

2021-08-29 09:15 UTC, xmatthias commented on user_data/strategies/MultiMa.py
> +# That can make signals by watching sort of Ribbon of sort of data.
That explanation does not really make sense.
You're kindof looping (i guess you mean that with ribbon, not a Ribbon on a package) - but what it tries to accomplish / compare is totally unclear.

2021-08-29 09:21 UTC, mablue commented on user_data/strategies/MultiMa.py
> +# That can make signals by watching sort of Ribbon of sort of data.
this explanation is totally have english grammer problems. and changed and will commited. now I just try to get good signals in live. It have signal generation problems cuz of massive conditions.

2021-09-15 18:38 UTC, xmatthias commented on user_data/strategies/Rainbow.py
> +# $ freqtrade hyperopt --hyperopt-loss SortinoHyperOptLossDaily --strategy Rainbow -c configusdt.json --eps
using `--eps` is missleading, as it'll end in results that cannot be recreated in live runs (which does not support position stacking).

i'd therefore not propose it here (you'll probably also need to reevaluate if the strategy is then still viable).

2021-09-15 18:41 UTC, xmatthias commented on user_data/strategies/Rainbow.py
> +    def ConditionGenerator(self, comperator, df, A, B):
As mentioned before - please familiarize yourself with python naming conventions.

The naming (uppercase first letter) suggests a class-name (also the syntax-highlighting does) - but in reality it's a function.

2021-09-15 19:39 UTC, xmatthias commented on user_data/strategies/Rainbow.py
> +# $ freqtrade hyperopt --hyperopt-loss SortinoHyperOptLossDaily --strategy Rainbow -c configusdt.json -e 10
`-e 10` will not produce any meaningful results.
As mentioned for the Xth time to you: Please read the documentation!!!!

Please either:
* Remove command examples that don't make sense
* or make them meaningfull.

It's absolutely pointless to have samples for each possible hyperoptloss function - and your $$$ comments don't make sense (especially not with the parameters used) and show me that you are again not even trying / testing the code you're contributing.

2021-09-17 10:31 UTC, xmatthias commented on user_data/strategies/Rainbow.py
> +                    self.sell_ma_rolling.value).mean().shift(shift-1)
The strategy is looking into the future, and therefore making one of the [common mistakes we have in our documentation](https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies)

2021-09-17 10:32 UTC, xmatthias commented on user_data/strategies/Rainbow.py
> +                    dataframe['B'] = dataframe.iloc[:, i-1].rolling(
Here too (probably) - although i don't really understand what "i" can become.

2021-09-18 04:12 UTC, mablue commented on user_data/strategies/Rainbow.py
> +                    dataframe['B'] = dataframe.iloc[:, i-1].rolling(
if i-1 > 0 or if always i >= 1 
So there is no negative value execution.

2021-09-18 11:14 UTC, xmatthias commented on user_data/strategies/Rainbow.py
> +                    dataframe['B'] = dataframe.iloc[:, i-1].rolling(
this might be true for this instance, but not for the one pointed out above in the other comment.

2021-11-04 18:13 UTC, mablue commented
Multima is ok ! new Strategy Borned! :)

2021-11-04 18:13 UTC, closed without merging