Ichess Strategy added
freqtrade/freqtrade-strategies pull request #231
Opened 2021-11-05 20:44 UTC by mablue

![forex-comparic-photo-392-of-564](https://user-images.githubusercontent.com/5004900/140576105-2726c561-8f21-42f6-874f-8120b48b458b.jpg)
# Ichess Strategy  ichimoku_score
# Associate various ichimoku signals with a score. 
# For example, bullish signal => positive score, 
# and bearish signal => negative score. If the total score is above 0, it may indicate a bullish trend . 
# Otherwise, if it is below 0, it may indicate a bearish trend . 
# We used two smoothed moving averages to find the trend.
# More info:
# https://github.com/freqtrade/freqtrade-strategies/issues/97
# https://www.tradingview.com/script/P1bybHZA-Ichimoku-Cloud-Signal-Score-v2-0-0/
# Author: @Mablue (Masoud Azizi)
# github: https://github.com/mablue/

2021-11-06 07:21 UTC, xmatthias commented on user_data/strategies/Ichess.py
> +        ).cumsum()
this will not work identically during backtesting and live runs.
backtesting has all data available - so you'll calculate this on a range of potentially 100ds of days (the end value can be pretty high).
You should instead use `.rolling().cumsum()` (didn't check for other such problems in this strategy ...).

2021-11-06 18:37 UTC, xmatthias commented on user_data/strategies/Ichess.py
> +        df['tkCrossScore'] = df.apply(calcTkCross, axis=1)
This is a very slow way of doing things.
i don't see any reason not to do this in a vectorized manner - which will be a lot quicker.

2021-11-18 16:40 UTC, mablue commented on user_data/strategies/Ichess.py
> +        ).cumsum()
thanks but I got two errors:
`TypeError: rolling() missing 1 required positional argument: 'window'`
which window is best default for rolling?
after add a number `.rolling(9).cumsum()`
`AttributeError: 'Rolling' object has no attribute 'cumsum'`
Whats the best change for fix?

2021-11-18 16:42 UTC, mablue commented on user_data/strategies/Ichess.py
> +        df['tkCrossScore'] = df.apply(calcTkCross, axis=1)
oh than what can we do?!! you said befour i can use dt.hour! can I use some thing like dt.hour instade of that, here?

2021-11-18 18:04 UTC, xmatthias commented on user_data/strategies/Ichess.py
> +        df['tkCrossScore'] = df.apply(calcTkCross, axis=1)
please do your own research - pandas is a wide enough topic so you can find probably 100ds of resources there - i'd suggest to properly learn pandas first.

2021-11-24 15:51 UTC, xmatthias requested changes
`np.vectorize` is NOT what i meant, and will have no performance benefit over using `apply()`. it's the equivalent to `pd.apply` - which both execute the function n times (n = number of rows).


A vectorized approach is for example the following: `dataframe['whatever'] = dataframe['low'] / dataframe['high']` - which is operating on series, not on single values.

2021-11-24 16:45 UTC, mablue commented
> `np.vectorize` is NOT what i meant, and will have no performance benefit over using `apply()`. it's the equivalent to `pd.apply` - which both execute the function n times (n = number of rows).
> 
> A vectorized approach is for example the following: `dataframe['whatever'] = dataframe['low'] / dataframe['high']` - which is operating on series, not on single values.

Okay thanks👌👌👌 I think I will work more on it than ;)

2022-05-10 14:49 UTC, mablue commented
I reached good things about this strategy!
Now this strategy splited to two versions and I just want to keep one of them! The one that is insane! But the normal one is good and simple!-_-

2022-12-30 16:59 UTC, froggleston commented
I see no updates to this PR that address the review so would recommend this is closed and reopened if any further work has been done.

2022-12-31 07:56 UTC, closed without merging